language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

#services:
#    - mysql

before_script:
    - composer self-update
    - composer install --no-ansi
    - mkdir -p build/logs

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then CM=""; NC=""; else CM=""; NC="--no-coverage"; fi
    - $CM ./vendor/bin/phpunit --configuration phpunit.xml $NC

after_script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then
        echo "We now have these coverage files:";
        ls -l build/logs;
        echo "Sending codeclimate report:";
        vendor/bin/test-reporter --coverage-report build/logs/clover.xml;
        echo "Sending codecov report:";
        TRAVIS_CMD="" bash <(curl -s https://codecov.io/bash) -f build/logs/clover.xml;
      fi

notifications:
    urls:
      - https://webhooks.gitter.im/e/b33a2db0c636f34bafa9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

    slack:
        rooms:
            - agiletoolkit:bjrKuPBf1h4cYiNxPBQ1kF6c#dsql
        on_success: change

    urls:
      - https://webhooks.gitter.im/e/c4000ab24556b09cb3e7

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

    email: false
